#!/bin/bash

# Script para eliminar el check antiguo de Oracle Monitor en Checkly
# Este script te guiará para eliminar el check antiguo que tiene la API key hardcodeada

echo "🗑️  Eliminando el check antiguo de Oracle Monitor en Checkly..."
echo ""
echo "📋 Pasos a seguir:"
echo ""
echo "1. Ve a: https://app.checklyhq.com/"
echo "2. Inicia sesión si es necesario"
echo "3. En el dashboard, busca los checks con el nombre 'Oracle Free Tier Monitor'"
echo "4. Deberías ver DOS checks con ese nombre:"
echo "   - Uno NUEVO (creado por CLI, ID: oracle-monitor-check)"
echo "   - Uno ANTIGUO (creado manualmente, ID diferente)"
echo ""
echo "5. Identifica el check ANTIGUO:"
echo "   - Abre el check y ve a la configuración"
echo "   - En 'Headers', verás el valor de X-API-Key"
echo "   - Si el valor es 'sgh7f78g789sf89g984895wtette4et423te4r0x8bb86sgfg867d' → Es el ANTIGUO"
echo "   - Si el valor es '{{ORACLE_MONITOR_API_KEY}}' → Es el NUEVO (no lo borres)"
echo ""
echo "6. Elimina SOLO el check antiguo:"
echo "   - Click en el check antiguo"
echo "   - Click en el menú '...' (tres puntos)"
echo "   - Selecciona 'Delete check'"
echo "   - Confirma la eliminación"
echo ""
echo "✅ Una vez eliminado, el check antiguo con la API key expuesta habrá desaparecido."
echo ""
echo "🔍 Verificación:"
echo "   Después de eliminar, deberías tener solo UN check 'Oracle Free Tier Monitor'"
echo "   que usa la variable de entorno {{ORACLE_MONITOR_API_KEY}}"
echo ""

read -p "Presiona ENTER cuando hayas completado estos pasos..."

echo ""
echo "✅ Perfecto. Ahora vamos a verificar que el nuevo check funciona."
echo ""
echo "Para verificar manualmente:"
echo "  1. Ve a https://app.checklyhq.com/"
echo "  2. Busca 'Oracle Free Tier Monitor'"
echo "  3. Click en 'Run check' para ejecutarlo manualmente"
echo "  4. Verifica que el resultado sea exitoso"
echo ""
echo "Si el check falla, es porque aún no has actualizado la API key en tu servidor Oracle."
echo "Ejecuta el script: ./scripts/update-oracle-api-key.sh en tu servidor Oracle."
echo ""
